[package]
name = "codec"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
